# Тестовые данные
GET http://localhost:4000/api HTTP/1.1

###

###

# Пользователи
## Создание нового пользователя (5.8)
POST http://localhost:4000/users/create HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "email": "torans48@overlook.net",
  "avatarPath": "torrance.png",
  "userType": "pro",
  "password": "123456"
}
###

## Вход в закрытую часть приложения (5.9)
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans48@overlook.net",
  "password": "123456"
}
###
## Выход из закрытой части приложения (5.10)
DELETE  http://localhost:4000/users/logout HTTP/1.1
Content-Type: application/json
###

## Проверка состояния пользователя (5.11)
GET  http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json
###

# Предложения
## Создание нового предложения (5.1)
POST http://localhost:4000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczQ4QG92ZXJsb29rLm5ldCIsImlkIjoiNjNkNzc4MWQ2MDUwMTVkZGMwOGZjYWMzIiwiaWF0IjoxNjc1NDA2MTgzLCJleHAiOjE2NzU1Nzg5ODN9.fIEQfjuOCL74ByO_AlKjx4ceL4MVkVWn_0AZaTcZnjE

{
  "title": "Offer 1055",
  "description": "Предложения 1055",
  "postDate": "2023-01-25T08:20:40.283Z",
  "city": "dfg",
  "prevImg": "img100.jpg",
  "image": ["photo100.jpg", "photo102.jpg", "photo103.jpg", "photo104.jpg", "photo105.jpg", "photo106.jpg"],
  "isPremium": true,
  "isFavorite":true,
  "rating": 2,
  "type": "room",
  "rooms": 1,
  "guests":2,
  "price": 1,
  "goods": ["Breakfast"]
}
###

## Редактирование предложения (5.2)
PATCH http://localhost:4000/offers/63d77401a03b664cf3e1055d HTTP/1.1
Content-Type: application/json

{
  "isPremium": true
}
###

## Удаление предложения по аренде (5.3)
DELETE  http://localhost:4000/offers/63d77401a03b664cf3e1056d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczQ4QG92ZXJsb29rLm5ldCIsImlkIjoiNjNkNzc4MWQ2MDUwMTVkZGMwOGZjYWMzIiwiaWF0IjoxNjc1NDA2MTgzLCJleHAiOjE2NzU1Nzg5ODN9.fIEQfjuOCL74ByO_AlKjx4ceL4MVkVWn_0AZaTcZnjE

###

## Получить список предложений по аренде (5.4)
GET http://localhost:4000/offers?limit=4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXI0QG1haWwuY29tIiwiaWQiOiI2M2Q3NzQwMWEwM2I2NjRjZjNlMTA1NjciLCJpYXQiOjE2NzU0NTIyODksImV4cCI6MTY3NTYyNTA4OX0.RgBgsLhgjBjcY3dEuA4w0xS_vivDDDxTbrbQPNnN4GQ

###

## Детальная информация по предложению (5.5)
GET http://localhost:4000/offers/63d77401a03b664cf3e1055d HTTP/1.1
Content-Type: application/json
###

## Список комментариев для предложения (5.6)
GET http://localhost:4000/offers/63d77401a03b664cf3e1055d/comments HTTP/1.1

###

## Добавление комментария (5.7)
POST http://localhost:4000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczQ4QG92ZXJsb29rLm5ldCIsImlkIjoiNjNkNzc4MWQ2MDUwMTVkZGMwOGZjYWMzIiwiaWF0IjoxNjc1NDA2MTgzLCJleHAiOjE2NzU1Nzg5ODN9.fIEQfjuOCL74ByO_AlKjx4ceL4MVkVWn_0AZaTcZnjE

{
  "text": "hdjdfj",
  "offerId": "63d77401a03b664cf3e1055d",
  "rating": 5
}

###
## Премиальные предложения для города (5.12)
GET http://localhost:4000/offers/premium/Paris HTTP/1.1
###

## Список избранных предложений (5.13)
GET http://localhost:4000/offers/favorite HTTP/1.1
###

## Добавление и удаление предложения в/из избранного (5.14)
PATCH http://localhost:4000/offers/favorite/63d77401a03b664cf3e1055d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InVzZXI0QG1haWwuY29tIiwiaWQiOiI2M2Q3NzQwMWEwM2I2NjRjZjNlMTA1NjciLCJpYXQiOjE2NzU0NTIyODksImV4cCI6MTY3NTYyNTA4OX0.RgBgsLhgjBjcY3dEuA4w0xS_vivDDDxTbrbQPNnN4GQ

###

## Отправка аватарки пользователю

POST http://localhost:4000/users/63d77401a03b664cf3e10556/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
Content-Type: image/png

< mocks/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
