# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

###

# Пользователи
## Создание нового пользователя (5.8)
POST http://localhost:4000/users/create HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "email": "lgv11@gmail.com",
  "userType": "pro",
  "password": "qwerty121"
}
###

## Вход в закрытую часть приложения (5.9)
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "rrr@rr.ru",
  "password": "qwerty12"
}
###

## Проверка состояния пользователя (5.11)
GET  http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

###

# Предложения
## Создание нового предложения (5.1)
POST http://localhost:4000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDY0NjEzLCJleHAiOjE2NzY2Mzc0MTN9.lCQpOMWKlrGeTsD7fqAkhTyNmO-Fja4IBrSvAPIM5_A

{
  "title": "Offerrr 178",
  "description": "Предложения ПредложенияПредложенияПредложения1055",
  "postDate": "2023-01-25T08:20:40.283Z",
  "city": "Paris",
  "isPremium": true,
  "isFavorite":false,
  "rating": 2,
  "type": "room",
  "rooms": 1,
  "guests":2,
  "price": 1000,
  "goods": ["Breakfast"]
}
###

## Редактирование предложения (5.2)
PATCH http://localhost:4000/offers/63ed53a472f444bc9f8ff655 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

{
  "isPremium": true
}
###

## Удаление предложения по аренде (5.3)
DELETE  http://localhost:4000/offers/63ed53a472f444bc9f8ff655 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDY0NjEzLCJleHAiOjE2NzY2Mzc0MTN9.lCQpOMWKlrGeTsD7fqAkhTyNmO-Fja4IBrSvAPIM5_A

###

## Получить список предложений по аренде (5.4)
GET http://localhost:4000/?limit=10 HTTP/1.1
Content-Type: application/json
///Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

###

## Детальная информация по предложению (5.5)
GET http://localhost:4000/offers/63ec0405754ee984dbe33272 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

###

## Список комментариев для предложения (5.6)
GET http://localhost:4000/offers/63ec0405754ee984dbe33272/comments HTTP/1.1

###

## Добавление комментария (5.7)
POST http://localhost:4000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

{
  "text": "hdjdfj",
  "offerId": "63ec0405754ee984dbe33272",
  "rating": 5
}

###
## Премиальные предложения для города (5.12)
GET http://localhost:4000/premium?city=Hamburg HTTP/1.1
###

## Список избранных предложений (5.13)
GET http://localhost:4000/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

###

## Добавление предложения в избранные (5.14)
POST http://localhost:4000/favorite/63ec0405754ee984dbe33272 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

###

## Удаление предложения из избранного (5.14)
DELETE http://localhost:4000/favorite/63ec0405754ee984dbe33272 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

###

## Отправка аватарки пользователю

POST http://localhost:4000/users/63e78e21f8ebb4149764844b/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
Content-Type: image/png

< mocks/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Загрузка превью для предложения
POST http://localhost:4000/offers/63ec0405754ee984dbe33272/previewimage HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="prevImg"; filename="room.jpg"
Content-Type: image/png

< ./mocks/img/room.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Загрузка изображений для предложения
POST http://localhost:4000/offers/63ec0405754ee984dbe33272/images HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJyckByci5ydSIsImlkIjoiNjNlYTU5MzM2MDM5M2IzMTc5M2VkNmJmIiwiaWF0IjoxNjc2NDEzNjkyLCJleHAiOjE2NzY1ODY0OTJ9.KshK1jHkm0oMvme1-rK5sEHivn8LPhOM-G2StXFMQB0


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="room.jpg"
Content-Type: image/png

< ./mocks/img/room.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="avatar-max.jpg"
Content-Type: image/png

< ./mocks/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="apartment-02.jpg"
Content-Type: image/png

< ./mocks/img/apartment-02.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="apartment-01.jpg"
Content-Type: image/png

< ./mocks/img/apartment-01.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="apartment-01.jpg"
Content-Type: image/png

< ./mocks/img/apartment-01.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="apartment-01.jpg"
Content-Type: image/png

< ./mocks/img/apartment-01.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
